### ISSUE TITLE
Filtrowanie lub oznaczanie obiektów nieistniejących

### ISSUE THREAD

**Issue by czupirek** [Eccenux/wlm-zabytki-mapa#8]
Są różne wersje oznaczania, że coś nie istnieje, proponuję przyjąć (najprostsza jest) `P31:Q19860854` (nieistniejący obiekt budowlany).

W zapytaniu sczytującym WD wystarczy do parametrów w SELECT dołożyć `?type`, bo i tak jest już to brane pod uwagę w joinach - wówczas nie będzie to miało dużego wpływu na wydajność samego zapytania.

Funkcjonalnie można by potem już na poziomie aplikacji odsiać to, co nie istnieje i oznaczyć np. szarą pinezką (albo w ogóle nie pokazywać, ale wg mnie lepiej jednak zostawić).

**Comment by Eccenux** [comment]
Przykład (Cybularny):
> Czy ten element nie jest obiektem tylko historycznie istniejącym (np. w przedwojennym rejestrze) albo źle zgeokodowanym? Bo obecnie to miejsce jest niezabudowane, a sama ulica Żabia nie dotrwała do naszych czasów. Jeśli to pierwsze, to pinezka zbędna. https://www.wikidata.org/wiki/Q33602603

Alternatywną dla specjalnego oznaczania mogłoby być całkowite odfiltrowanie tego rodzaju zabytków.

**Comment by czupirek** [comment]
Inne dane do testów - budynki w Słupsku:
https://www.wikidata.org/wiki/Q30626392?uselang=pl
https://www.wikidata.org/wiki/Q30626436?uselang=pl

Mapka w tym rejonie: https://zabytki.toolforge.org/#!?c=54.4642:17.0321:19

**Comment by Eccenux** [comment]
Dodałem filtrowanie zgodnie z sugestiami z Discorda.
https://zabytki.toolforge.org/#!?c=54.4641:17.0320:17
